### ISSUE TITLE
When is first open doesn't show the log in window

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#20]
In start.js script you are listing all accounts, but when the user haven't any account start() line is no executing so the app crash and doesn't open.

**Comment by burhan-project-manager** [comment]
Thanks to point that bug. It is fixed!

**Comment by jorge9200** [comment]
it is not fixed, when the user has no accounts, the callback returns [] object, and your code thinks that there is one or more account.

![image](https://user-images.githubusercontent.com/8724844/33323511-f94a76e0-d44c-11e7-938e-12deced81878.png)

**Comment by burhan-project-manager** [comment]
Yes you are right. It is now fixed!

**Comment by jorge9200** [comment]
@burhan-project-manager  solved, but take a look to this issue: #27
