### ISSUE TITLE
Attachments is not working

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#5]
When you attach some files to an email an send it. The receiver can't open the attachments, they are corrupted.

![image 4](https://user-images.githubusercontent.com/8724844/32487956-622ff50c-c3ab-11e7-827c-4f4d54c20ab4.png)

**Comment by burhan-project-manager** [comment]
We are just sending fsnodeID of attachment that your API is providing. 
I think there is some problem with your API where you are sending attachment to Gmail.

**Comment by jorge9200** [comment]
Nacho please can you take a look of this?

**Comment by icastillejogomez** [comment]
![captura de pantalla 2017-11-21 a las 3 43 12 pm](https://user-images.githubusercontent.com/16567802/33078353-b579d2c8-ced2-11e7-95aa-b5d324f3a09b.png)
fixed it!!

**Comment by burhan-project-manager** [comment]
File is still not downloading and every time file name is "attachment-1..*"

![image](https://user-images.githubusercontent.com/28291997/33111275-fb94ac64-cf6e-11e7-8bcc-e4026be44cf9.png)

**Comment by jorge9200** [comment]
@icastillejogomez can you take a look of this again please?

**Comment by icastillejogomez** [comment]
try again please and let me know if works or not

![captura de pantalla 2017-11-24 a las 3 42 36 pm](https://user-images.githubusercontent.com/16567802/33214949-2d5256f0-d12e-11e7-8fbb-f9170fde8650.png)

**Comment by burhan-project-manager** [comment]
Yes it is working fine now. Thanks

**Comment by jorge9200** [comment]
it seems working! closed
